services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app_web
    volumes:
      - ../src/public:/app
    ports:
      - "8000:8000"
   

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
