services:
  app:
    container_name: back-app
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      -../src:/var/www 
    
  nginx:
    image: nginx:1.29-alpine 
    container_name: server-nginx
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d